### ISSUE TITLE
请问此插件如何使用？

### ISSUE THREAD

**Issue by konnyakuxzy** [JaxsonWang/Wp-HyperMD#1]
似乎还在开发中？QwQ
听说挺好用的，请问怎么用呢？
打扰作者大大了Orz

**Comment by JaxsonWang** [comment]
现阶段可以正常使用的。下载安装即可

**Comment by konnyakuxzy** [comment]
@JaxsonWang 我下载了以后在插件目录中执行命令：
`composer install`
成功以后上传成功启用，但是文章编辑页并未有Markdown编辑器显示（也就是HyperMD的界面没显示）
但是如果发布文章是能成功解析MD语法的
而且安装老版本（Meow-Editor）是能使用的。
不知道是不是我姿势不正确？

**Comment by JaxsonWang** [comment]
我这有些功能没完善，暂时用老版本的吧。主要提交wp库遇到问题了
