### ISSUE TITLE
评论尚不支持MD

### ISSUE THREAD

**Issue by MuenYu** [JaxsonWang/Wp-HyperMD#4]
经测试，评论MD尚不支持

复现：[这里](https://mashiro.best/links/)

请作者确认这是否达到了你理想的效果，其他功能完好，谢谢！

**Comment by remmina** [comment]
@MuenYu 刚刚测试了一下，怀疑是主题的锅？
因为我博客用的也是HyperMD，但是是可以实现Markdown评论的
Markdown的那些关键字，比如`#`以及无序列表都被转成了`<p></p>`
这说明Markdown解析是存在的
所以换个主题试试？

**Comment by MuenYu** [comment]
@remmina 刚刚测试在你的网站上也测试了一下，发现效果和我是一样的 0.0

//不过话说`#`不应该被转成`<h1></h1>`这样么 0v0

**Comment by remmina** [comment]
@MuenYu 

![image](https://user-images.githubusercontent.com/47842757/53243363-8eee4700-36e2-11e9-8fb5-e5ccaeb3ff31.png)

**Comment by remmina** [comment]
@MuenYu 刚刚实验了一下发现如果是登录的用户就可以正确解析

这个应该是权限的设定了，可能是有设定未登录用户不予以解析

有可能是wordpress本身的设定，也有可能是插件的设定

我去找找。。。

**Comment by remmina** [comment]
@MuenYu 问题已经找到了，是wordpress为了安全，只允许游客评论发送一小部分html标签，像`<code>`和`<p>`这种

如果要解决可以这样：

打开Wordpress的`function.php`，在文件末尾添加：

```php
function allow_more_tag_in_comment() {
	global $allowedtags;
	$allowedtags['h1'] = array('class'=>array());
	$allowedtags['h2'] = array('class'=>array());
	$allowedtags['h3'] = array('class'=>array());
	$allowedtags['ul'] = array('class'=>array());
}

add_action('init', 'allow_more_tag_in_comment',11);
```

这段代码将会允许游客评论中出现`h1`,`h2`,`h3`（三种标题）,`ul`（无序列表）的标签

所以问题并不是插件的，而是Wordpress的机制导致的\_(:зゝ∠)\_

**Comment by MuenYu** [comment]
@remmina 大佬666，加个友链呗~

**Comment by remmina** [comment]
@MuenYu 好呀OvO
已经给您加上啦
友联名称给您写的是`MuenYu`，如果想更改的话联系我的邮箱吧（感觉直接在issue里搞不太好.jpg）
